version: '3'
services:
  wireguard-server:
    image: ${DOCKER_REGISTRY}monstrenyatko/wireguard-server
    container_name: wireguard-server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${WIREGUARD_SERVER_CONFIG}:/etc/wireguard/wg0.conf:ro
    ports:
      - ${WIREGUARD_SERVER_PORT}:${WIREGUARD_SERVER_PORT}/udp
